//const load = [/*"effects",*/"dropler", "platinum", "sawburst", "breach", "voltcoil", "synth", "nanite-station", "mod" ].map(i => require(i));
require("blocks/dropler");
require("platinum");
require("blocks/sawburst");
require("blocks/breach");
require("blocks/volliage");
require("blocks/synth");
require("blocks/nanite-station");
require("mod");
require("metal-eating-organism");
require("libs/techTree");
require("zeneloth");
// require("blocks/sigma");